# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
